odom_ekf:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    world_frame: odom
    odom_frame: odom
    base_link_frame: base_link
    two_d_mode: true

    odometry0: /odom
    odometry0_config: [false, false, false, true, true, false, true, true, true, false, false, false, true, false, false]
    odometry0_differential: false

    imu0: /imu
    imu0_config: [true, true, false, false, false, true, false, false, true]
    imu0_differential: false
